<a href="https://colab.research.google.com/github/aarongraybill/Math210/blob/main/ProblemSets/ProblemSet3/ProblemSet3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Math 210
## Aaron Graybill
### Problem Set 3
### 3/4/21

## Problem 1.

In [3]:
## Dot Product:
import numpy as np

def dot(v1,v2):
  out=0
  for idx, x in np.ndenumerate(v1): #iterator location and value
    out = out + v1[idx]*v2[idx]
  return out

dot(np.array([1,2,3]),np.array([1,2,3]))

14

In [4]:
## Outer Product

def outer(v1,v2):
  out=np.empty((v1.shape[0],v2.shape[0])) #define empty matrix
  for i in range(v1.shape[0]): #one iter for each row
    out[i,:]=v1[i]*v2 # multiply each row vector by the current scalar
  return out

outer(np.array([1,2,3]),np.array([1,2,3]))


array([[1., 2., 3.],
       [2., 4., 6.],
       [3., 6., 9.]])

In [5]:
## Transpose
#This code is quite cute i think

def transp(a) :
  out=np.empty((a.shape[1],a.shape[0])) #make empty matrix of right dims
  for idx, x in np.ndenumerate(a): #iterator location and value
    out[idx[1],idx[0]] = x #give current value to opposite index
  return out

In [6]:
# You can run this to test your codes
v1 = np.array([1,4,5,6])
v2 = np.array([2,1,3,8])
result1 = dot(v1,v2)
print(result1)
print()
result2 = outer(v1,v2)
print(result2)
print()
a = np.array([[1,4,6,7],[2,3,9,8]])
print(a)
#print()
m = transp(a)
print(m)

69

[[ 2.  1.  3.  8.]
 [ 8.  4. 12. 32.]
 [10.  5. 15. 40.]
 [12.  6. 18. 48.]]

[[1 4 6 7]
 [2 3 9 8]]
[[1. 2.]
 [4. 3.]
 [6. 9.]
 [7. 8.]]


## Problem 2.


### a.


In [60]:
# Problem 2a -- implements the Target step of SimplexBF
#      Input: tableau "a" (just the numbers, no labels)
#      Output: the column number where the largest c is located
#                 except if all c's are <= 0, then return -1
#              (in giving the column a number, use human numbering, i.e., first column is 1 not 0)
# 
def target(a) :
    nrows,ncols = a.shape #define row and column nums
    if np.max(a[nrows-1,:-1])<0: #if highest val <0, return -1 (don't check constant)
        return -1
    else: 
      bestcol = np.argmax(a[nrows-1,:])+1 #return the maximizing place +1 (for readibility)
      return bestcol


### b. 

In [125]:

# Problem 2b -- implements the Candidates/Select step of SimplexBF
#      Two Inputs: tableau "a" (just the numbers, no labels)
#               and column number "pivcolnum" where the Target lives
#      Output: the row number for the pivot that SimplexBF would choose
#                 except if all aij's in this column are <= 0, then return -1
#     
#     NOTE: for both the input column number and the output row number,
#               please use human numbering, i.e., first column or row is 1 not 0
#  
def select(a,pivcolnum) :
    bestratio=np.inf #initial value that anything will be better than
    nrows = a.shape[0]    # use the shape function to determine number of rows and cols in A
    ncols = a.shape[1]
    rownum="Something is wrong if you're seeing this"
    if max(a[:-1,pivcol-1])<=0:#prevents checking the obj function
      rownum =-1
    else:
      for i in range(nrows-1): #don't check obj function
        ratio=a[i,ncols-1]/a[i,pivcolnum-1]
        if ratio<bestratio:
          bestratio=ratio
          rownum=i+1

# You fill in the rest.  In your code, define "rownum" to equal the row number for the pivot
    return rownum;

In [129]:
# This cell could be useful for you to test the two functions above
import numpy as np
a = np.array([[10,5,150],   # This is the bakery-problem "a"
         [4,3,80],          # target should return column = 1
         [30,20,0]])        # and then select should return row = 1
                            # If you swap the 30 and 20, column and row should change to 2 

                                                    
pivcol=target(a)
print(pivcol)
pivrow=select(a,pivcol)
print("pivot on row ",pivrow," and column ",pivcol)

pivot on row  2  and column  1
