__Creating vectors and matrices__

In [14]:
# Here's one way to handle a vector in Python: as a one-dimensional array in the package numpy
# Execute this cell to see that it works
import numpy as np
w = np.array([1, 4, 5, 6, 7])
print(w)

[1 4 5 6 7]


In [15]:
# To create a matrix, we use similar syntax:
a = np.array([  [1, 3, 5], [2, 4, 6] ])
print(a)
# This gives us a way to make a column vector:
v = np.array([ [1], [4], [5], [6], [7]])
print()   # this is just a blank line
print(v)

[[1 3 5]
 [2 4 6]]

[[1]
 [4]
 [5]
 [6]
 [7]]


__Accessing entries in a vector or a matrix__

In [16]:
# Here's how you access entries in a vector or a matrix.  
# Note that Python (like many programming languages) labels the first row, or the first column
#     as index 0 rather than as index 1
print(v[0])
print(v[2])
print(a[0][0])
print(a[1][2])

[1]
[5]
1
6


In [ ]:
# Notice that entering, displaying, and extracting entries from column vectors is a bit annoying.
# As a result, some may prefer to just use row vectors and remember that we mean it to be a column

__For loops__

In [17]:
# "For loops" allow you to repeat an action, with an integer tracking your progress
# For example, 
#       for i in range(n) 
# will make "i" visit the integers 0, 1, 2, ..., n-1

for i in range(5):
    print(i)

0
1
2
3
4


In [19]:
# Since vectors are also indexed starting at 0, we can use "for" and "range" to scan over entries of a vector
w = np.array([1, 4, 5, 6, 7])
for i in range(5):
    print("entry  ",i," is ",w[i])

entry   0  is  1
entry   1  is  4
entry   2  is  5
entry   3  is  6
entry   4  is  7


In [20]:
# We can use this idea to build a vector from another vector.  For example,
#    Here's an example of using a loop to create a vector that is v "read backwards"
w = np.array([1,4,5,6,7])
wnew = w.copy()         # This command makes a copy of w, so wnew has the desired number of entries
for i in range(5):      # Now we use the loop to fill in the values we want
    wnew[i] = w[4-i]
print(w)
print(wnew) 

[1 4 5 6 7]
[7 6 5 4 1]


In [23]:
# We can also use a for loop to compute a sum
w = np.array([1,4,5,6,7])
sum = 0     # Initialize a variable to be zero, will accumulate the sum as we scan over the entries of w
for i in range(5):
    sum = sum + w[i]     # This command takes the old value of "sum", adds w[i] to it, and makes that the new value
print(sum)

23


__Double loops___

In [22]:
# If you put one "for loop" inside another, you can cycle through the entries of a matrix:
a = np.array([[1, 3, 5],[2,4,6]])
print(a)
for i in range(2):
    for j in range(3):
        print("entry in row ",i," and column ",j," is ",a[i][j])

[[1 3 5]
 [2 4 6]]
entry in row  0  and column  0  is  1
entry in row  0  and column  1  is  3
entry in row  0  and column  2  is  5
entry in row  1  and column  0  is  2
entry in row  1  and column  1  is  4
entry in row  1  and column  2  is  6


__Three exercises for you to do; some fundamental computations in linear
algebra: the dot product, the outer product (which is a key component
of the pivot computation), and the transpose__

In [31]:
def dot_prod(v1,v2) :
    # Inputs:   two vectors v1, v2 with the same number of entries
    # Output:   the dot product of the vectors
    n = v1.shape[0]    # The number of entries in v1 (and hence in v2 as well)
    #
    # You fill in what goes here to compute the dot product, call it "x"
    #
    return x

In [32]:
def outer_prod(v1,v2) :
    # Inputs: two vectors v1, v2 with the same number of entries
    # Output: the matrix v1 v2^T (when v1, v2 are considered to be column vectors)
    n = v1.shape[0]    # This determines how many entries are in v1 (and hence in v2 as well)
    a = np.empty([n,n])    # This sets up "a" to be a matrix with the correct number of rows and columns
    #
    # You fill in what goes here to compute the entries of "a"
    #
    return a

In [33]:
def transp(a) :
    # Input: a (a matrix)
    # Output: the matrix a^T
    m = a.shape[0]   # This determines the number of rows in a
    n = a.shape[1]   # This determines the number of columns in a
    #
    # You fill in what goes here to compute the entries of the transpose, call it "b"
    #
    return b

In [ ]:
# You can run this to test your codes
v1 = np.array([1,4,5,6])
v2 = np.array([2,1,3,8])
result1 = dot_prod(v1,v2)
print(result1)
print()
result2 = outer_prod(v1,v2)
print(result2)
print()
a = np.array([[1,4,6,7],[2,3,9,8]])
print(a)
print()
m = transp(a)
print(m)